# Generated by Django 5.2.6 on 2025-09-24 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(help_text='Seat number like 12A', max_length=5)),
                ('seat_class', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=10)),
                ('seat_status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='available', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='seat',
            name='airplane',
        ),
        migrations.DeleteModel(
            name='SpecialFlight',
        ),
        migrations.AddField(
            model_name='airplane',
            name='business_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airplane',
            name='capacity',
            field=models.PositiveIntegerField(default=100, help_text='Total number of seats'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='economy_seats',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='airplane',
            name='first_class_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text="Use Decimal('123.45')", max_digits=12),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddField(
            model_name='flightseat',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_seats', to='airport.flight'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='airport.flightseat'),
        ),
        migrations.AddConstraint(
            model_name='flightseat',
            constraint=models.UniqueConstraint(fields=('flight', 'seat_number'), name='unique_seat_per_flight'),
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
