# Generated by Django 5.2.6 on 2025-09-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_flightseat_remove_seat_airplane_delete_specialflight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightseat',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
