# Generated by Django 5.2.6 on 2025-10-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_remove_ticket_order_remove_payment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='code',
            field=models.CharField(default='XXX', help_text='IATA airline code (e.g., AA, BA)', max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name='airplane',
            name='registration',
            field=models.CharField(default='N000XX', help_text='Aircraft registration (e.g., N123AA)', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.CharField(default='Unknown', help_text='City where airport is located', max_length=100),
        ),
        migrations.AddField(
            model_name='airport',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Airport timezone (e.g., America/New_York)', max_length=50),
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='XX', help_text='ISO 3166-1 alpha-2 code (e.g., US, GB)', max_length=2, unique=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, help_text='Actual arrival time', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='actual_departure',
            field=models.DateTimeField(blank=True, help_text='Actual departure time', null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='gate',
            field=models.CharField(blank=True, help_text='Departure gate', max_length=10),
        ),
        migrations.AlterField(
            model_name='airline',
            name='airports',
            field=models.ManyToManyField(blank=True, related_name='airlines', to='airport.airport'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='seat_map',
            field=models.JSONField(blank=True, default=list, help_text='List of seat definitions with seat_number and seat_class'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(db_index=True, help_text='IATA code (e.g., JFK, LHR)', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(help_text='Scheduled arrival time (UTC)'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base economy class price', max_digits=12),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(db_index=True, help_text='Flight date for grouping and searching'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(db_index=True, help_text='Scheduled departure time (UTC)'),
        ),
        migrations.AddConstraint(
            model_name='airplane',
            constraint=models.UniqueConstraint(fields=('airline', 'registration'), name='unique_registration_per_airline'),
        ),
    ]
