# Generated by Django 5.1.7 on 2025-12-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_airline_code_airplane_registration_airport_city_and_more'),
    ]

    operations = [
        # The code fields were already added to the database in migration 0003
        # using RunSQL, but Django's state wasn't updated. This migration
        # only updates Django's state without modifying the database.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No database operations needed - fields already exist
            ],
            state_operations=[
                migrations.AddField(
                    model_name='airline',
                    name='code',
                    field=models.CharField(default='XXX', help_text='IATA airline code (e.g., AA, BA)', max_length=3, unique=True),
                ),
                migrations.AddField(
                    model_name='country',
                    name='code',
                    field=models.CharField(default='XX', help_text='ISO 3166-1 alpha-2 code (e.g., US, GB)', max_length=2, unique=True),
                ),
            ],
        ),
    ]
