# Generated by Django 5.2.6 on 2025-09-25 11:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_flightseat_is_reserved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='processing', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='flight',
            name='unique_flight_number_per_airline',
        ),
        migrations.RemoveConstraint(
            model_name='flightseat',
            name='unique_seat_per_flight',
        ),
        migrations.RemoveConstraint(
            model_name='ticket',
            name='ticket_price_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_active_ticket_per_seat_on_flight',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='final_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='business_seats',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='economy_seats',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='first_class_seats',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='flightseat',
            name='is_reserved',
        ),
        migrations.RemoveField(
            model_name='flightseat',
            name='seat_class',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='airplane',
            name='seat_map',
            field=models.JSONField(default=list, help_text='List of seat definitions'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='date for unique flight instances'),
        ),
        migrations.AddField(
            model_name='flightseat',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When seat was reserved/locked', null=True),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airplanes', to='airport.airline'),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Total number of seats'),
        ),
        migrations.AlterField(
            model_name='airport',
            name='code',
            field=models.CharField(db_index=True, help_text='IATA code', max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airports', to='airport.country'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Base ticket price', max_digits=12),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(db_index=True, help_text='UTC datetime'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='flight',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=15),
        ),
        migrations.AlterField(
            model_name='flightseat',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='airport.flight'),
        ),
        migrations.AlterField(
            model_name='flightseat',
            name='seat_number',
            field=models.CharField(db_index=True, help_text='Seat number like 12A', max_length=10),
        ),
        migrations.AlterField(
            model_name='flightseat',
            name='seat_status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], db_index=True, default='available', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='booked', max_length=20),
        ),
        migrations.AddIndex(
            model_name='airplane',
            index=models.Index(fields=['airline'], name='airport_air_airline_912db0_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['airline', 'flight_number'], name='airport_fli_airline_7efdaf_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['departure_airport', 'arrival_airport'], name='airport_fli_departu_d24267_idx'),
        ),
        migrations.AddIndex(
            model_name='flightseat',
            index=models.Index(fields=['flight', 'seat_status'], name='airport_fli_flight__3fa041_idx'),
        ),
        migrations.AddConstraint(
            model_name='flight',
            constraint=models.UniqueConstraint(fields=('airline', 'flight_number', 'departure_date'), name='unique_flight_number_per_airline_per_day'),
        ),
        migrations.AddConstraint(
            model_name='flightseat',
            constraint=models.UniqueConstraint(fields=('flight', 'seat_number'), name='unique_seat_per_flight_sparse'),
        ),
        migrations.AddField(
            model_name='order',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='airport.flight'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='airport.order'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['order'], name='airport_tic_order_i_bf6a67_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['seat'], name='airport_tic_seat_id_b49839_idx'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='ticket_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='airport_ord_user_id_ad18a9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['flight'], name='airport_ord_flight__877390_idx'),
        ),
    ]
