# Generated by Django 5.2.6 on 2025-10-09 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Remaining coupon balance', max_digits=12)),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Original coupon amount', max_digits=12)),
                ('stripe_coupon_id', models.CharField(blank=True, help_text='Stripe coupon ID', max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Coupon expiry date', null=True)),
                ('description', models.TextField(blank=True, help_text='Coupon description/reason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='stripe_paym_user_id_013904_idx'), models.Index(fields=['status'], name='stripe_paym_status_ed723e_idx'), models.Index(fields=['expires_at'], name='stripe_paym_expires_5bb079_idx')],
            },
        ),
    ]
