# Generated by Django 5.2.6 on 2026-01-04 13:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airport', '0004_airline_code_country_code'),
        ('stripe_payment', '0003_payment_coupon_payment_discount_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_occupancy', models.IntegerField(help_text='Maximum number of guests', validators=[django.core.validators.MinValueValidator(1)])),
                ('bed_type', models.CharField(blank=True, help_text="e.g., '1 King Bed', '2 Twin Beds'", max_length=50)),
                ('room_size_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Room size in square meters', max_digits=6, null=True)),
                ('amenities', models.JSONField(blank=True, default=list, help_text='Room-specific amenities')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('distance_from_airport_km', models.DecimalField(decimal_places=2, help_text='Distance from airport in kilometers', max_digits=6)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('star_rating', models.IntegerField(default=3, help_text='Hotel star rating (1-5)', validators=[django.core.validators.MinValueValidator(1)])),
                ('amenities', models.JSONField(blank=True, default=list, help_text="List of amenities (e.g., ['wifi', 'pool', 'gym', 'parking'])")),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nearest_airport', models.ForeignKey(help_text='Nearest airport', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nearby_hotels', to='airport.airport')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, help_text='Base price per night', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_available', models.BooleanField(default=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('view_type', models.CharField(blank=True, choices=[('city', 'City View'), ('ocean', 'Ocean View'), ('garden', 'Garden View'), ('airport', 'Airport View'), ('none', 'No View')], default='none', max_length=50)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hotels.roomtype')),
            ],
            options={
                'ordering': ['hotel', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_nights', models.IntegerField(help_text='Calculated automatically', validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_guests', models.IntegerField(help_text='Number of guests', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night at time of booking', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for all nights', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Any discount applied', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('guest_name', models.CharField(max_length=200)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotels.hotel')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_bookings', to='stripe_payment.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_bookings', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hotels.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['nearest_airport', 'is_active'], name='hotels_hote_nearest_9b8d2e_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['city', 'country'], name='hotels_hote_city_a01868_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['user', 'status'], name='hotels_hote_user_id_828c79_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['hotel', 'check_in_date', 'check_out_date'], name='hotels_hote_hotel_i_1840e9_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelbooking',
            index=models.Index(fields=['room', 'check_in_date', 'check_out_date'], name='hotels_hote_room_id_82dfe2_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'is_available'], name='hotels_room_hotel_i_134e5e_idx'),
        ),
    ]
