# Generated by Django 5.2.6 on 2025-09-23 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Example +380501234567', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{7,15}$', 'Write phone number')]),
        ),
    ]
