# Generated by Django 5.2.6 on 2025-10-01 10:39

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_google_id'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
